//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheCorcoranGroup.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class President
    {
        public int id { get; set; }
        public string name { get; set; }
        public string birthday { get; set; }
        public string birthplace { get; set; }
        public string deathday { get; set; }
        public string deathplace { get; set; }
    }
}
